version: '3.9'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5433:5432"

    expose:
      - 5433
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}