# Generated by Django 3.2.23 on 2023-11-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20231108_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('shop', 'Магазин'), ('buyer', 'Покупатель')], default='Покупатель', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
