# Generated by Django 3.2.23 on 2023-11-08 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Категория(Category)', 'verbose_name_plural': 'Список категорий(Category)'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты пользователя(Contact)', 'verbose_name_plural': 'Список контактов пользователя(Contact)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-dt',), 'verbose_name': 'Заказ(Order)', 'verbose_name_plural': 'Список заказов(Order)'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанная позиция(OrderItem)', 'verbose_name_plural': 'Список заказанных позиций(OrderItem)'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Название параметра(Parameter)', 'verbose_name_plural': 'Список названий параметров(Parameter)'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-article', '-name', '-category'), 'verbose_name': 'Продукт(Product)', 'verbose_name_plural': 'Перечень номенклатуры(Product)'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Данные о продукте(Pricat)', 'verbose_name_plural': 'Список данных о продуктах(Pricat)'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр товара(ProductParameter)', 'verbose_name_plural': 'Список параметров товара(ProductParameter)'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-name'], 'verbose_name': 'Магазин(Shop)', 'verbose_name_plural': 'Список магазинов(Shop)'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь(User)', 'verbose_name_plural': 'Список пользователей(User)'},
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название параметра'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='backend_api.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для загрузки приката'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('article', 'name'), name='unique_product_name'),
        ),
    ]
